### ISSUE TITLE
create_gem fails if there is output from different aligners in output directory

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#189]
I've been testing the example data on Palmetto this weekend and I stumbled upon this error by chance. I had run the example data with hisat2 and then again with salmon. Because I didn't clear out my output directory, create_gem during the salmon actually picked up the tpm files from both aligners, which caused the error.

So we need to either modify create_gem to select the files for the current aligner or add this error to the troubleshooting docs.
```
Command executed:

  create_gem.sh     true     false     /home/btsheal/workspace/gemmaker     output     CORG_vs_samples     true     true

Command exit status:
  1

Command output:
  /home/btsheal/workspace/gemmaker/output/SRX218012/SRX218012_vs_CORG.Hisat2.tpm
  /home/btsheal/workspace/gemmaker/output/SRX218012/SRX218012_vs_CORG.Salmon.tpm
  /home/btsheal/workspace/gemmaker/output/2/2_vs_CORG.Salmon.tpm
  /home/btsheal/workspace/gemmaker/output/2/2_vs_CORG.Hisat2.tpm
  /home/btsheal/workspace/gemmaker/output/1/1_vs_CORG.Salmon.tpm
  /home/btsheal/workspace/gemmaker/output/1/1_vs_CORG.Hisat2.tpm
  /home/btsheal/workspace/gemmaker/output/3/3_vs_CORG.Hisat2.tpm
  /home/btsheal/workspace/gemmaker/output/3/3_vs_CORG.Salmon.tpm
  
  Found 8 sample files
  Adding results for sample: SRX218012
  Adding results for sample: SRX218012

Command error:
  Traceback (most recent call last):
    File "/home/btsheal/workspace/gemmaker/bin/create-gem.py", line 72, in <module>
      ematrix = ematrix.merge(df.iloc[:,[0,1]], on='gene', how='outer')
    File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 7334, in merge
      validate=validate,
    File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py", line 81, in merge
      validate=validate,
    File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py", line 630, in __init__
      self._maybe_coerce_merge_keys()
    File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py", line 1138, in _maybe_coerce_merge_keys
      raise ValueError(msg)
  ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat
```

**Comment by spficklin** [comment]
Fixed with PR #211
