### ISSUE TITLE
The trimmomatic docker/singularity image might be missing & Directive 'validExitStatus' has been deprecated

### ISSUE THREAD

**Issue by fmobegi** [SystemsGenetics/GEMmaker#191]
Am trying to run GEMmaker with docker but it keeps failing because of a missing trimmomatic image. 

Also, validExitStatus seems to raise a warning

````
WARN: Directive 'validExitStatus' has been deprecated -- Check process 'write_stage_files'
WARN: Directive 'validExitStatus' has been deprecated -- Check process 'start_first_batch'
WARN: Directive 'validExitStatus' has been deprecated -- Check process 'read_sample_file'
WARN: Directive 'validExitStatus' has been deprecated -- Check process 'fastqc_1'
WARN: Directive 'validExitStatus' has been deprecated -- Check process 'trimmomatic'
```

**Comment by spficklin** [comment]
Hi @fmobegi . Thanks much for providing feedback!  We are aware of the deprecated `validExitStatus` and have a fix already applied in our development branch, so that warning should go away on the next release of GEMmaker.

I just tested pulling the trimmomatic image and it worked just fine, so I'm not able to reproduce the problem you're experiencing.  Can you post any error messages you are getting from Trimmomatic?

**Comment by fmobegi** [comment]
First, it seems like the main.nf cannot find trimmomatic.sh script in the project bin directory. I don't know how to best replicate that
```
fredrick@cicer:/ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm$ nextflow run GEMmaker/main.nf -profile singularity -resume
N E X T F L O W  ~  version 20.04.1
Launching `GEMmaker/main.nf` [drunk_hopper] - revision: 7bd3d08206

===================================
 G E M M A K E R   P I P E L I N E
===================================

Workflow Information:
---------------------
  Project Directory:  /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/GEMmaker
  Launch Directory:   /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm
  Work Directory:     /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/work
  Config Files:       [/ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/GEMmaker/nextflow.config, /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/nextflow.config]
  Container Engine:   singularity
  Profile(s):         singularity


Input Parameters:
-----------------
  Remote fastq list path:     /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/none
  Local sample glob:          /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/*_{R1,R2}.fq.gz


Quantification Tool Input:
--------------------------
  Use Hisat2:                 true
  Hisat2 Index Prefix:        ME14
  Hisat2 GTF File:            ME14.gtf
  Hisat2 Index Directory:     ME14

  Use Kallisto:               false
  Kallisto Index File:        CORG.transcripts.Kallisto.indexed

  Use Salmon:                 false
  Salmon Index Directory:     CORG.transcripts.Salmon.indexed


Output Parameters:
------------------
  Output directory:           output
  Publish SRA:                false
  Publish downloaded FASTQ:   false
  Publish trimmed FASTQ:      true
  Publish BAM:                true
  Publish Gene Abundance:     false
  Publish GTF_GA:             true
  Publish RAW:                true
  Publish FPKM:               true
  Publish TPM:                false
  MultiQC:                    true
  Create GEM:                 true


Execution Parameters:
---------------------
  Queue size:                 2


Software Parameters:
--------------------
  Trimmomatic clip path:      /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/TruSeq3-PE.fa
  Trimmomatic minimum ratio:  0.7

executor >  local (187)
[-        ] process > retrieve_sra_metadata                           -
[e0/44d8b4] process > write_stage_files (15CUR003_L_2_L004)           [100%] 174 of 174 ✔
[18/74d598] process > start_first_batch                               [100%] 1 of 1 ✔
[d0/949bfd] process > read_sample_file (15CUR003_E_1_L004.sample.csv) [100%] 2 of 2
[-        ] process > next_sample                                     -
[-        ] process > download_runs                                   -
[-        ] process > fastq_dump                                      -
[-        ] process > fastq_merge                                     -
[-        ] process > fastqc_1 (15CUR003_E_1_L003)                    -
[-        ] process > kallisto                                        -
[-        ] process > kallisto_tpm                                    -
[-        ] process > salmon                                          -
[-        ] process > salmon_tpm                                      -
[87/076df5] process > trimmomatic (15CUR003_E_1_L004)                 [100%] 7 of 7, failed: 7, retries: 6
[-        ] process > fastqc_2                                        -
[-        ] process > hisat2                                          -
[-        ] process > samtools_sort                                   -
[-        ] process > samtools_index                                  -
[-        ] process > stringtie                                       -
[-        ] process > hisat2_fpkm_tpm                                 -
[-        ] process > multiqc                                         -
[-        ] process > create_gem                                      -
[-        ] process > clean_sra                                       -
[-        ] process > clean_fastq                                     -
[-        ] process > clean_merged_fastq                              -
[-        ] process > clean_trimmed_fastq                             -
[-        ] process > clean_sam                                       -
[-        ] process > clean_bam                                       -
[-        ] process > clean_kallisto_ga                               -
[-        ] process > clean_salmon_ga                                 -
[-        ] process > clean_stringtie_ga                              -
WARN: Killing pending tasks (3)
Error executing process > 'trimmomatic (15CUR003_E_1_L003)'

Caused by:
  Process `trimmomatic (15CUR003_E_1_L003)` terminated with an error exit status (1)

Command executed:

  trimmomatic.sh 15CUR003_E_1_L003 0.7 1 TruSeq3-PE.fa 3 6 4:15 -phred33

Command exit status:
  1

Command output:
  3

Command wrapper:
  3

Work dir:
  /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/work/d3/64fbe7a80116da5909a7959e81feaf

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```
# The content of the working dir:
```
fredrick@cicer:/ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm$ cat /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/work/d3/64fbe7a80116da5909a7959e81feaf/.command.sh 
#!/bin/bash -ue
trimmomatic.sh 15CUR003_E_1_L003 0.7 1 TruSeq3-PE.fa 3 6 4:15 -phred33
## and the log file
fredrick@cicer:/ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm$ cat /ppgdata/fredrick/assembly_data/ascochyta/2020-10-06-RNAseq_analysis/01_raw_data/test_genm/work/d3/64fbe7a80116da5909a7959e81feaf/15CUR003_E_1_L003.trim.log 
TrimmomaticPE: Started with arguments:
 -threads 1 15CUR003_E_1_L003_1.fastq 15CUR003_E_1_L003_2.fastq 15CUR003_E_1_L003_1p_trim.fastq 15CUR003_E_1_L003_1u_trim.fastq 15CUR003_E_1_L003_2p_trim.fastq 15CUR003_E_1_L003_2u_trim.fastq ILLUMINACLIP:TruSeq3-PE.fa:2:40:15 LEADING:3 TRAILING:6 SLIDINGWINDOW:4:15 MINLEN:-nan
Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'AAAAAAAAAAAAAAAAAAAAAAAAAAA'
Using Long Clipping Sequence: 'GGGGGGGGGGGGGGGGGGGGGGGGGGG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG'
Using Long Clipping Sequence: 'TTTTTTTTTTTTTTTTTTTTTTTTTTT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT'
Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
Using Long Clipping Sequence: 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'
Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
ILLUMINACLIP: Using 2 prefix pairs, 20 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Exception in thread "main" java.lang.NumberFormatException: For input string: "-nan"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.usadellab.trimmomatic.trim.MinLenTrimmer.<init>(MinLenTrimmer.java:11)
	at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:56)
	at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
```
I have got the standard profile running after hard-coding the trimmomatic step in main.nf
```
  """
  java -jar ${params.software.trimmomatic.jarfile} PE \
  -threads ${task.cpus} -phred33 \
  ${sample_id}_1.fq.gz ${sample_id}_2.fq.gz \
  -baseout ${sample_id}_trim.fq.gz \
  MINLEN:${params.software.trimmomatic.MINLEN} \
  ILLUMINACLIP:TruSeq3-PE.fa:2:40:15 \
  LEADING:${params.software.trimmomatic.LEADING} \
  TRAILING:${params.software.trimmomatic.TRAILING} \
  SLIDINGWINDOW:${params.software.trimmomatic.SLIDINGWINDOW} \
  > ${sample_id}.trim.log 2>&1
  
  """
```

Sorry I couldn't be able to replicate the problem fully

**Comment by spficklin** [comment]
Hi @fmobegi if you would like to share your configuration file I'd be happy to try and help you resolve the problem.

**Comment by fmobegi** [comment]
[nextflow.config.txt](https://github.com/SystemsGenetics/GEMmaker/files/5419227/nextflow.config.txt)

Thats the config file am currently using on https://pawsey.org.au/systems/nimbus-cloud-service/

**Comment by spficklin** [comment]
Hi @fmobegi .  Sorry for the very slow reply.  So your config file looks okay.  But judging by the output file you posted above it seems that trimmomatic is failing with this error: 

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "-nan"
```
Did I understand correctly that you were able to get passed his problem by hard-coding the java command for trimmomatic in the `main.nf` file?

**Comment by spficklin** [comment]
Okay. I just figured out what was wrong and I can reproduce the error.

The problem is that the files have a `.gz` extension.  They are gzipped.  GEMmaker currently doesn't support fastq files that are gzipped.  So, when ?GEMmaker runs it is actually passing the .gz file to trimmomatic but renames it without the .gz extension.  So trimmomatic, which can handle gzipped fastq files, doesn't realize it's gzipped and gives the error message.

The short easy fix is to just uncompress your fastq files. The correct fix is to make GEMmaker support gzipped files.  I'm going to mark this as a bug for us to fix.

**Comment by fmobegi** [comment]
I got the standard version to work with the config file I had shared earlier.
## Modifying the trimmomatic step in `main.nf`:

```
process trimmomatic {
  publishDir params.output.sample_dir, mode: params.output.publish_mode, pattern: publish_pattern_trimmomatic
  tag { sample_id }
  label "multithreaded"
  label "trimmomatic"

  input:
    set val(sample_id), file("${sample_id}_?.fq.gz") from HISAT2_CHANNEL
    file fasta_adapter from FASTA_ADAPTER

  output:
    set val(sample_id), file("${sample_id}_trim_*.fq.gz") into TRIMMED_SAMPLES_FOR_FASTQC
    set val(sample_id), file("${sample_id}_trim_*.fq.gz") into TRIMMED_SAMPLES_FOR_HISAT2
    set val(sample_id), file("${sample_id}_trim_*.fq.gz") into TRIMMED_FASTQ_FOR_CLEANING
    set val(sample_id), file("${sample_id}.trim.log") into TRIMMED_SAMPLE_LOG

  script:
  """
  java -jar ${params.software.trimmomatic.jarfile} PE \
  -threads ${task.cpus} -phred33 \
  ${sample_id}_1.fq.gz ${sample_id}_2.fq.gz \
  -baseout ${sample_id}_trim.fq.gz \
  MINLEN:${params.software.trimmomatic.MINLEN} \
  ILLUMINACLIP:TruSeq3-PE.fa:2:40:15 \
  LEADING:${params.software.trimmomatic.LEADING} \
  TRAILING:${params.software.trimmomatic.TRAILING} \
  SLIDINGWINDOW:${params.software.trimmomatic.SLIDINGWINDOW} \
  > ${sample_id}.trim.log 2>&1

  """
}
```
## Modifying the bin/hisat2.sh script:
```
#!/bin/bash

sample_id="$1"
params_input_reference_name="$2"
task_cpus="$3"


if [ -e ${sample_id}_trim_2P.fq.gz ]; then
  hisat2 \
    -x ${params_input_reference_name} \
    --no-spliced-alignment \
    -q \
    -1 ${sample_id}_trim_1P.fq.gz \
    -2 ${sample_id}_trim_2P.fq.gz \
    -U ${sample_id}_trim_1U.fq.gz,${sample_id}_trim_2U.fq.gz \
    -S ${sample_id}_vs_${params_input_reference_name}.sam \
    -t \
    -p ${task_cpus} \
    --un ${sample_id}_un.fastq \
    --dta-cufflinks \
    --new-summary \
    --summary-file ${sample_id}_vs_${params_input_reference_name}.sam.log
else
  hisat2 \
    -x ${params_input_reference_name} \
    --no-spliced-alignment \
    -q \
    -U ${sample_id}_trim_1U.fq.gz \
    -S ${sample_id}_vs_${params_input_reference_name}.sam \
    -t \
    -p ${task_cpus} \
    --un ${sample_id}_un.fastq \
    --dta-cufflinks \
    --new-summary \
    --summary-file ${sample_id}_vs_${params_input_reference_name}.sam.log
fi
```
I was interested in <fastqc-trimmomatic-fastqc-hisat2-stringtie-multiqc> path and all the first 3 tools handle .gz files.

**Comment by spficklin** [comment]
Okay sounds great. Glad you got it to work with your tweaks.  We will keep this issue open so we can fix the `.gz` problem.

**Comment by spficklin** [comment]
The issue of not support gzipped files is fixed with PR #218
