### ISSUE TITLE
GEMMAKER broken at metadata retrieval again

### ISSUE THREAD

**Issue by feltus** [SystemsGenetics/GEMmaker#276]
### Description of the bug

Gemmaker is dying at sra metadata retrieval again. I did a clean pull so I should be using latest version.  This worked before, so maybe something changed at SRA again?

Error executing process > 'GEMmaker:retrieve_sra_metadata'

Caused by:
  Process `GEMmaker:retrieve_sra_metadata` terminated with an error exit status (1)

### Command used and terminal output

```console
[ffeltus@node0770 ath_gem]$ module add  openjdk/11.0.15_10-gcc/9.5.0
[ffeltus@node0770 ath_gem]$ nextflow pull systemsgenetics/gemmaker
Checking systemsgenetics/gemmaker ...
 Already-up-to-date - revision: c7fe33612e [master]
[ffeltus@node0770 ath_gem]$ nextflow run systemsgenetics/gemmaker -profile test,singularity
N E X T F L O W  ~  version 22.10.7
Launching `https://github.com/systemsgenetics/gemmaker` [extravagant_liskov] DSL2 - revision: c7fe33612e [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  systemsgenetics/gemmaker v2.1.1
------------------------------------------------------
Core Nextflow options
  revision                  : master
  runName                   : extravagant_liskov
  containerEngine           : singularity
  launchDir                 : /scratch1/ffeltus/ath_gem
  workDir                   : /scratch1/ffeltus/ath_gem/work
  projectDir                : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker
  userName                  : ffeltus
  profile                   : test,singularity
  configFiles               : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/nextflow.config

Input/output options
  input                     : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/*{1,2}.fastq
  pipeline                  : hisat2
  sras                      : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/SRA_IDs.txt
  skip_samples              : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/samples2skip.txt
  failed_run_report_template: /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/failed_sra_runs.template.html
  multiqc_config_file       : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/multiqc_config.yaml
  multiqc_custom_logo       : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/systemsgenetics-gemmaker_logo.png

Kallisto Pipeline
  kallisto_index_path       : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/references/CORG.transcripts.Kallisto.indexed
  kallisto_bootstrap_samples: 0

Salmon Pipeline
  salmon_index_path         : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/references/CORG.transcripts.Salmon.indexed

Hisat Pipeline
  hisat2_base_name          : CORG
  hisat2_index_dir          : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/references/CORG.genome.Hisat2.indexed
  hisat2_gtf_file           : /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/references/CORG.transcripts.gtf

Reference genome options
  igenomes_ignore           : true

Generic options
  publish_dir_mode          : link

Max job request options
  max_cpus                  : 2
  max_memory                : 6 GB
  max_time                  : 2d

Institutional config options
  config_profile_name       : Test profile
  config_profile_description: Minimal test dataset to check pipeline function

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use systemsgenetics/gemmaker for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.3620945

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/systemsgenetics/gemmaker/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > GEMmaker:get_software_versions -
[-        ] process > GEMmaker:retrieve_sra_metadata -
[-        ] process > GEMmaker:download_runs         -
[-        ] process > GEMmaker:get_software_versions -
[-        ] process > GEMmaker:retrieve_sra_metadata [  0%] 0 of 1
[-        ] process > GEMmaker:download_runs         -
executor >  local (1)
[-        ] process > GEMmaker:get_software_versions -
[29/d2f8d5] process > GEMmaker:retrieve_sra_metadata [  0%] 0 of 1
executor >  local (1)
[-        ] process > GEMmaker:get_software_versions -
[29/d2f8d5] process > GEMmaker:retrieve_sra_metadata [  0%] 0 of 1
[-        ] process > GEMmaker:download_runs         -
[-        ] process > GEMmaker:fastq_dump            -
[-        ] process > GEMmaker:fastq_merge           -
[-        ] process > GEMmaker:fastqc_1              -
[-        ] process > GEMmaker:trimmomatic           -
[-        ] process > GEMmaker:fastqc_2              -
[-        ] process > GEMmaker:hisat2                -
[-        ] process > GEMmaker:samtools_sort         -
[-        ] process > GEMmaker:samtools_index        -
[-        ] process > GEMmaker:stringtie             -
[-        ] process > GEMmaker:stringtie_fpkm_tpm    -
[-        ] process > GEMmaker:next_sample           -
[-        ] process > GEMmaker:multiqc               -
[-        ] process > GEMmaker:create_gem            -
[-        ] process > GEMmaker:failed_run_report     -
[-        ] process > GEMmaker:clean_work_files      -
[-        ] process > GEMmaker:clean_work_dirs       -
Pulling Singularity image docker://systemsgenetics/gemmaker:2.1.0 [cache /scratch1/ffeltus/ath_gem/work/singularity/systemsgenetics-gemmaker-2.1.0.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /scratch1/ffeltus/ath_gem/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'GEMmaker:retrieve_sra_metadata'

Caused by:
  Process `GEMmaker:retrieve_sra_metadata` terminated with an error exit status (1)

Command executed:

  echo "#TRACE n_remote_run_ids=`cat SRA_IDs.txt | wc -l`"

  # Remove the 'path:' prefix. This was added to prevent
  # Nextflow from recoginzing the path and noticing the work
  # directory changed and trying to re-run this process even
  # if it succeeded.
  workdir=`echo path:/scratch1/ffeltus/ath_gem/work/GEMmaker | sed 's/path://'`

  retrieve_sra_metadata.py       --run_id_file SRA_IDs.txt       --meta_dir "$workdir"       --out_file SRA_run2exp.tsv        --skip_file /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/samples2skip.txt

Command exit status:
  1

Command output:
  #TRACE n_remote_run_ids=1

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  #TRACE n_remote_run_ids=1
  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR/649/944'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR/649'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 289, in <module>
      missing_runs = find_downloaded_runs(meta_dir, run_ids)
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 214, in find_downloaded_runs
      run_dir = get_accession_directory(meta_dir, run_id)
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 195, in get_accession_directory
      pathlib.Path(dir).mkdir(parents=True, exist_ok=True)
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.pexecutor >  local (1)
[-        ] process > GEMmaker:get_software_versions -
[29/d2f8d5] process > GEMmaker:retrieve_sra_metadata [100%] 1 of 1, failed: 1 ?
[-        ] process > GEMmaker:download_runs         -
[-        ] process > GEMmaker:fastq_dump            -
[-        ] process > GEMmaker:fastq_merge           -
[-        ] process > GEMmaker:fastqc_1              -
[-        ] process > GEMmaker:trimmomatic           -
[-        ] process > GEMmaker:fastqc_2              -
[-        ] process > GEMmaker:hisat2                -
[-        ] process > GEMmaker:samtools_sort         -
[-        ] process > GEMmaker:samtools_index        -
[-        ] process > GEMmaker:stringtie             -
[-        ] process > GEMmaker:stringtie_fpkm_tpm    -
[-        ] process > GEMmaker:next_sample           -
[-        ] process > GEMmaker:multiqc               -
[-        ] process > GEMmaker:create_gem            -
[-        ] process > GEMmaker:failed_run_report     -
[-        ] process > GEMmaker:clean_work_files      -
[-        ] process > GEMmaker:clean_work_dirs       -
Pulling Singularity image docker://systemsgenetics/gemmaker:2.1.0 [cache /scratch1/ffeltus/ath_gem/work/singularity/systemsgenetics-gemmaker-2.1.0.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /scratch1/ffeltus/ath_gem/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'GEMmaker:retrieve_sra_metadata'

Caused by:
  Process `GEMmaker:retrieve_sra_metadata` terminated with an error exit status (1)

Command executed:

  echo "#TRACE n_remote_run_ids=`cat SRA_IDs.txt | wc -l`"

  # Remove the 'path:' prefix. This was added to prevent
  # Nextflow from recoginzing the path and noticing the work
  # directory changed and trying to re-run this process even
  # if it succeeded.
  workdir=`echo path:/scratch1/ffeltus/ath_gem/work/GEMmaker | sed 's/path://'`

  retrieve_sra_metadata.py       --run_id_file SRA_IDs.txt       --meta_dir "$workdir"       --out_file SRA_run2exp.tsv        --skip_file /home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/assets/demo/samples2skip.txt

Command exit status:
  1

Command output:
  #TRACE n_remote_run_ids=1

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  #TRACE n_remote_run_ids=1
  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR/649/944'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR/649'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META/SRR'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/ffeltus/ath_gem/work/GEMmaker/SRA_META'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 289, in <module>
      missing_runs = find_downloaded_runs(meta_dir, run_ids)
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 214, in find_downloaded_runs
      run_dir = get_accession_directory(meta_dir, run_id)
    File "/home/ffeltus/.nextflow/assets/systemsgenetics/gemmaker/bin/retrieve_sra_metadata.py", line 195, in get_accession_directory
      pathlib.Path(dir).mkdir(parents=True, exist_ok=True)
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1316, in mkdir
      self.parent.mkdir(parents=True, exist_ok=True)
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1316, in mkdir
      self.parent.mkdir(parents=True, exist_ok=True)
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1316, in mkdir
      self.parent.mkdir(parents=True, exist_ok=True)
    [Previous line repeated 1 more time]
    File "/opt/conda/envs/systemsgenetics-gemmaker-2.1.0/lib/python3.9/pathlib.py", line 1312, in mkdir
      self._accessor.mkdir(self, mode)
  OSError: [Errno 30] Read-only file system: '/scratch1/ffeltus/ath_gem/work/GEMmaker'

Work dir:
  /scratch1/ffeltus/ath_gem/work/29/d2f8d5fa40baf2007cba24e409f917

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`



[ffeltus@node0770 ath_gem]$
```

**Comment by feltus** [comment]
The problem was with BeeGFS,
