### ISSUE TITLE
HTTP Error 400 (Bad Request) on retrieve_sra_metadata.py

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#94]
This error is easiest to reproduce on the `issue-88` branch but it occurs on master as well:
```
$ python tests/retrieve_sra_metadata.py 
Traceback (most recent call last):
  File "tests/retrieve_sra_metadata.py", line 48, in <module>
    test_missing_SRR()
  File "tests/retrieve_sra_metadata.py", line 19, in test_missing_SRR
    download_runs_meta(test_set1)
  File "/home/eceftl3/workspace/GEMmaker/bin/retrieve_sra_metadata.py", line 51, in download_runs_meta
    response_obj = urllib.request.urlopen(request)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/eceftl3/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

The maddening part is that it doesn't always happen, I'll get the error on the first few attempts and then it will go away... I think. I'm not really sure what the deal is here but this bug and the ascp bug are driving me insane because they seem to be happening at random...

**Comment by spficklin** [comment]
Oh, I have seen a Bad Request error when none of the SRR numbers exist.  But that's a predictable test case.

**Comment by spficklin** [comment]
@bentsherman are you still experiencing this problem?

**Comment by spficklin** [comment]
To add to the previous question. We're not experiencing any problems with this script currently.

**Comment by bentsherman** [comment]
@spficklin I haven't seen this error in a while but I don't know if we ever did anything to deal with this bug. I think it's okay if we close this issue for now, and if I see it again I can reopen.

**Comment by spficklin** [comment]
Sounds good. Thanks.
